### ISSUE TITLE
Pressing 'P' crashes the game

### ISSUE THREAD

**Issue by Kewun0** [gtaco-op/vc-coop#17]
Not in chat, but when the chat is not open. P crashes.

**Comment by Kewun0** [comment]
It seems happens with 'Z' too.

**Comment by LemonHaze420** [comment]
Fixed in 039f8ab5651bd436595a1e0476f5f3732f9a3abd

**Comment by LemonHaze420** [comment]
(this was left over debug functionality and is not needed at all any more)
