### ISSUE TITLE
VCCoOp doesn't load in WINE

### ISSUE THREAD

**Issue by eFleka** [gtaco-op/vc-coop#20]
GTA VC starts normally instead of starting into vccoop in wine in linux.

**Comment by NicusorN5** [comment]
It might the version of VC you are using.

**Comment by eFleka** [comment]
I'm using GTA-VC 1.0.

**Comment by ZeyadAhmed** [comment]
we use #include <windows.h> but I think wine is for that virtualization, make simple asi (a c++ DLL) then use DLL injector see if it will be executed or use a DLL injector, also I saw before VCMP was played on wine and that is totally strange.

**Comment by eFleka** [comment]
VCMP runs great with WINE on my PC, so I don't think that's the issue.

**Comment by NicusorN5** [comment]
Are you using the Ultimate ASI Loader?

**Comment by eFleka** [comment]
No ASI loaders.

**Comment by ZeyadAhmed** [comment]
Will not be fixed, try windows dude
we use an asi loader since its not a winapi based executable then the asi loader can't load the asi/dll.
